name: WF_Otros

on:
  push:
    branches: 
      - '**'
      - '!main'
      - '!desarrollo' 
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
    branches: 
      - '**'
      - '!main'
      - '!desarrollo'

jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s tests -v
    - name: Cálculo de cubrimiento
      id: cubrimiento
      run: |
          coverage run -m unittest discover -s tests -v
          coverage report -m
  automerge:
    if: ${{ contains(github.event.head_commit.message, '[MERGE]') }}
    name: merge-branch
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2

      - name: Merge feature -> desarrollo
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: desarrollo
          github_token: ${{ github.token }}  